# Generated by Django 5.1.7 on 2025-03-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItemmodel',
        ),
        migrations.DeleteModel(
            name='Ordermodel',
        ),
    ]
