# Generated by Django 5.1.7 on 2025-04-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=100),
        ),
    ]
