# Generated by Django 5.1.7 on 2025-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0006_alter_order_summarymodel_order_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_summarymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order_summarymodel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_summarymodel',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
