# Generated by Django 5.1.7 on 2025-04-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0007_order_summarymodel_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Summarymodel',
        ),
    ]
