# Generated by Django 5.1.7 on 2025-04-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0013_order_summarymodel_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_summarymodel',
            name='items',
        ),
    ]
