# Generated by Django 5.1.7 on 2025-04-11 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0014_remove_order_summarymodel_items'),
        ('PRODUCTS', '0003_cartmodel_cartitemmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_order', to='ORDERS.orderitemmodel'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='PRODUCTS.productmodel'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
